### ISSUE TITLE
LRM Crashes during an unrealistically high rate of climb/descent

### ISSUE THREAD

**Issue by optoisolated** [lrmapp/issues#10]
When the aircraft is experiencing an unrealistic rate of climb/descent (due to non-competent pilot flying, or due to use of Slew mode), the LRM client will crash citing "Value was either too large or too small for an Int16." 

Is it possible for the LRM client to have an option to ignore excessive (or unrealistic) rates of climb/descent also?

<img width="330" alt="LRM-Crashed" src="https://user-images.githubusercontent.com/46586989/70380959-b622b600-198e-11ea-85a7-835264a1544c.png">

**Comment by optoisolated** [comment]
Hi, have you had a chance to take a look at this bug at all? Thanks 👍

**Comment by allebb** [comment]
Hey optoisolated,

I'm really sorry for the delay in getting back to you (I've been so busy recently) - Strangely I'm unable to replicate the issue though.

Can I ask what simulator and version you are using so I can attempt to replicate my end?

**Comment by optoisolated** [comment]
Hi, No worries at all :) I'm using FSX:SE (standard, not beta). You can replicate it by using something like an F-16 or other aircraft with high climb/descend rate, and disabling crash detection. I noticed it when my child was playing and I'd turned off crash detection.

**Comment by allebb** [comment]
Fantastic, thanks for the feedback. I'll add a fix in the next version of the client (due to be released later this month) 👍

**Comment by allebb** [comment]
Hi @optoisolated , I appreciate that it's been a while and you may have moved on from Simming/using another platform but I wanted to let you know that there is a new BETA release that can be found here: https://forums.fshub.io/t/lrm-client-beta-4-2-2-released-for-testing/36

I'd be interested in hearing if you still experience the same problem when using that version?

**Comment by allebb** [comment]
This has been fixed in the latest releases of LRM. Closing this issue as no further work is required.
