### ISSUE TITLE
LRM could use a "slew mode"

### ISSUE THREAD

**Issue by ecb0719** [lrmapp/issues#14]
I'm using LRM with P3Dv4.5. When I'm slewing around in-game, if I slew up, it outputs a takeoff report, when I come down, it Tries to output a landing report, but usually results in an application crash. The only way to then continue to use LRM is to restart my computer. It would be nice if there were a way to detect that the game was in slew mode and just go to a sleep or standby mode until exiting the slew.

**Comment by ecb0719** [comment]
In fact, I just took a look at  optoisolated's post. The crash I'm talking about produces the same Microsoft Framework error he has in his screenshot.

**Comment by allebb** [comment]
Hi @ecb0719, I appreciate that it's been a while and you may have moved on from Simming/using another platform but I wanted to let you know that there is a new BETA release that can be found here: https://forums.fshub.io/t/lrm-client-beta-4-2-2-released-for-testing/36

I'd be interested in hearing if you still experience the same problem when using that version?

**Comment by allebb** [comment]
Closing this aged issue/no response from user.
