### ISSUE TITLE
Landing rating

### ISSUE THREAD

**Issue by ESMP** [lrmapp/issues#15]
I've noticed that landing at less than 100 ft/sec shows "smooth" landing, but landing somewhere between 100 and 150 shows "perfect" landing. Shouldn't it be the other way around?

**Comment by allebb** [comment]
Good morning Eduardo,

No, that is actually 100% correct. A "perfect" landing is one that makes
"positive" contact to a runway surface. A landing between 100 and 150 FPM
ensures that the landing gear makes positive contact with the runway
surface and mitigates such events as aquaplaning, pilot error (the pilot
will definitely feel that he/she has landed) as well as a load of other
factors that you research online. So actually, although one may think that
a 0 (zero) FPM landing *may* be the best possible type of landing, that is
arguably incorrect and deemed very unsafe :)

I did a lot of research into what a "perfect" landing may measure as and
these parameters are configured as a result :)

I hope this helps and answers your concerns.

Cheers,
Bobby

**Comment by allebb** [comment]
Closing issue as per the above explanation of landing parameters and how this is correctly implemented.
