### ISSUE TITLE
Connection doesn't happen

### ISSUE THREAD

**Issue by zoubix** [lrmapp/issues#18]
Good morning.

Since last update, my LRM Client doesn't connect to my Xplane simulator despite XPUIPC is properly loaded.
Uninstalled and reinstalled several times, no improvement.
I checked the permissions in the Firewall, everything seems OK.

Any guidance for restoring the connection LRM Client with Xplane ?

Thank you.

**Comment by allebb** [comment]
Hi @zoubix,

I see that you seem to have successfully logged a flight through XP11 today - Can I, therefore, assume you have fixed this problem and I can close this issue now?

Kind regards,
Bobby

**Comment by zoubix** [comment]
Good morning.

Thanks for your answer.

Unfortunately the issue is not solved. 

I am currently using two PC simultaneously with one simulator running on each, that’s why you saw a flight that has been logged yesterday. LRM client is working fine on one PC, but I’m not able to make it connected on the second PC.

What I did until now trying to fix the issue :

1. Uninstall and reinstall (several times) even on different places on my hard drive 
2. Ensure permissions are OK
3. Reinstalled XPUIPC

And it is still not able to get connected to the sim.

Louis

**Comment by zoubix** [comment]
Any suggestion ?

**Comment by allebb** [comment]
Hi @zoubix sorry for the delay in getting back to you, here are a couple of ideas:-

1) Are you running the simulator using the Window's "Run As Administrator" feature?- If so, you will need to run LRM Client in the same mode. (FWIW I would recommend running both in standard mode!)
2) Check that X-Plane has correctly loaded the XPUIPC plugin and that it is enabled.

Other than that, *maybe* check that your virus scanner hasn't quarantined XPUIPC or LRM for some strange reason. 

I have no reason to personally think this is an LRM issue as you've already mentioned that it is running fine on your other computer and no one else has reported a similar issue at this point.

**Comment by zoubix** [comment]
Hi Bobby,

None of the solutions you proposed solved the issue.
As you said, it's likely coming from my PC settings rather from the LRM Client...
I will continue to search for a solution.
Thanks for your help anyway.

Louis

**Comment by allebb** [comment]
Hey Louis,

No problem - Sorry I can't be of more help. It might however be worth checking the XPUIPC/FSUIPC forums for suggestions/clues etc.

I'll close this issue as there is little I can really do without being able to replicate your issue and given that it is a local/XPUIPC/XP11 issue as opposed to LRM specifically.

👍
