### ISSUE TITLE
Windows 10. Application not start's

### ISSUE THREAD

**Issue by AlexDustin** [lrmapp/issues#3]
Hello. Im try to open application after installing with admins rights, but nothing happen. Not opening application. No any error. Silent. What wrong? 

Im try to instal in any place, but not help.

**Comment by frosenlind** [comment]
Same problem here.

**Comment by allebb** [comment]
Evening guys - sorry for the late reply on this one, I've been pretty busy recently but I'm working to do a release for this tomorrow.

I have a sneaky suspicion that this may be related to issue #2.

Version 2.4 should be released tomorrow with some cool new features too! :)

**Comment by allebb** [comment]
This has now been fixed and tested. The latest v2.4 release can be downloaded and installed from: http://lk2.in/fw

Please report back any issues but all should work fine regardless of your regional settings (of which  was found to have been the cause).
