### ISSUE TITLE
Feature request : add speed to the landing report

### ISSUE THREAD

**Issue by gaabne** [lrmapp/issues#4]
> Would you mind openig a separate issue (well, feature request) on GitHub for this request and I will work on getting that added this evening too.

Thanks you for taking into account my request.

> I suppose I could add an option to the LRM tool to "Display additional stats in-sim" which could then show the IAS at landing, wind speed etc.

I vote for the option solution and **Yes** I would **love** to get it on the green in-sim ticker. (I always minimize the desktop app display.)

Can't wait :)

Cheers
Gérard

**Comment by allebb** [comment]
Cool - I will get this added after work and get the release out this evening.

**Comment by allebb** [comment]
This has now been added to the application, To enable the extra settings, goto "File > Settings" and then enable the "Show extra landing statistics in the sim".

You can download the latest vesion here: http://lk2.in/fw

Thanks for requesting and I hope you enjoy the new feature :)
