### ISSUE TITLE
Stays Disconnected

### ISSUE THREAD

**Issue by Romeo037** [lrmapp/issues#9]
Hey 

I just downloaded the LRM addon for fsx, i installed it correctly but when i launsh it ( the software and FSX ) it says disconnected. 
I can't find a way of connecting it to the simulator.

Any help is appreciated 

Romeo

**Comment by allebb** [comment]
Hi Romeo037 - If you're using X-Plane you'll need to first install and configure XPUIPC, if using FS2004, FSX or P3D you'll need to download and install FSUIPC.

Both XPUIPC and FSUIPC are both free to download and install.

You should be able to follow the documentation here: https://client.lrmlive.com/docs/LRM-Client-Documentation_v4.0.0.pdf

Please let me know if you still have issues.

Cheers,
Bobby

**Comment by allebb** [comment]
Hey Romeo037,

Just wondered if you managed to get it to work in the end? - If I don't hear back from you within 5 days I'll assume all worked fine and will close this issue :)

Cheers,
Bobby

**Comment by Romeo037** [comment]
Sorry i forgot to hit you Back, everything is working fine now.

Thank you for your help
Romeo

**Comment by allebb** [comment]
Great - Thanks Romeo, I'll close the issue! 👍 Hope you're enjoying LRM/FSHub!
